# Generated by Django 4.2.4 on 2023-08-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loanrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="offer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="loanrequest",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="loanrequest",
            name="start_date",
        ),
    ]
