# Generated by Django 4.2.4 on 2023-08-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0002_alter_loanrequest_options_alter_offer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanrequest",
            name="loan_period",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
