# Generated by Django 4.2.4 on 2023-08-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0003_alter_loanrequest_loan_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="scheduledpayment",
            name="is_last_payment",
            field=models.BooleanField(default=False),
        ),
    ]
