# Generated by Django 4.2.4 on 2023-08-19 21:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0004_offer_status_scheduledpayment_is_last_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanrequest",
            name="lenme_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="loanrequest",
            name="loan_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.01,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="scheduledpayment",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.01,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
